# Generated by Django 5.0.3 on 2024-04-09 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_sent', to=settings.AUTH_USER_MODEL)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_provided', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_address', models.CharField(max_length=255)),
                ('sender_contact', models.CharField(max_length=50)),
                ('service_provider_name', models.CharField(max_length=100)),
                ('service_provider_address', models.CharField(max_length=255)),
                ('service_provider_contact', models.CharField(max_length=50)),
                ('delivery_completion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverycompletion')),
            ],
        ),
    ]
