# Generated by Django 5.0.3 on 2024-04-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_serviceproviders_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviders',
            name='bank_account1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceproviders',
            name='bank_account2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
